[2025-06-13T11:24:58.744+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-13T11:24:58.771+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exemplo_dag_simples.executar_funcao_python scheduled__2025-06-12T00:00:00+00:00 [queued]>
[2025-06-13T11:24:58.783+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exemplo_dag_simples.executar_funcao_python scheduled__2025-06-12T00:00:00+00:00 [queued]>
[2025-06-13T11:24:58.784+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-06-13T11:24:58.800+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): executar_funcao_python> on 2025-06-12 00:00:00+00:00
[2025-06-13T11:24:58.808+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=266) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-13T11:24:58.809+0000] {standard_task_runner.py:72} INFO - Started process 269 to run task
[2025-06-13T11:24:58.810+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exemplo_dag_simples', 'executar_funcao_python', 'scheduled__2025-06-12T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/exemplo-dag.py', '--cfg-path', '/tmp/tmp5_pbhz21']
[2025-06-13T11:24:58.813+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask executar_funcao_python
[2025-06-13T11:24:58.831+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-13T11:24:58.880+0000] {task_command.py:467} INFO - Running <TaskInstance: exemplo_dag_simples.executar_funcao_python scheduled__2025-06-12T00:00:00+00:00 [running]> on host 3f818eaf31a0
[2025-06-13T11:24:58.883+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-13T11:24:58.977+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='exemplo_dag_simples' AIRFLOW_CTX_TASK_ID='executar_funcao_python' AIRFLOW_CTX_EXECUTION_DATE='2025-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-12T00:00:00+00:00'
[2025-06-13T11:24:58.979+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-13T11:24:58.995+0000] {logging_mixin.py:190} INFO - Executando DAG de exemplo no Airflow!
[2025-06-13T11:24:58.996+0000] {logging_mixin.py:190} INFO - Data e hora atual: 2025-06-13 11:24:58.996265
[2025-06-13T11:24:58.997+0000] {python.py:240} INFO - Done. Returned value was: Task executada com sucesso!
[2025-06-13T11:24:59.027+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-13T11:24:59.029+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=exemplo_dag_simples, task_id=executar_funcao_python, run_id=scheduled__2025-06-12T00:00:00+00:00, execution_date=20250612T000000, start_date=20250613T112458, end_date=20250613T112459
[2025-06-13T11:24:59.068+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-13T11:24:59.105+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-13T11:24:59.110+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
